---
before_script:
  - ruby -v
  - bundle -v
  - gem --version
  - rm Gemfile.lock || true
  - rm -rf ~/.bundle/ ~/.gem/bundler/ ~/.gems/cache/bundler/
  - rm -rf $GEM_HOME/bundler/ $GEM_HOME/cache/bundler/
  - rm -rf .bundle/
  - rm -rf vendor/cache/
  - gem uninstall rubygems-bundler open_gem
  - touch /tmp/aaaaaaaa
  - ls -la /tmp
  - df -k
  - mount
  - ruby -e 'require "tmpdir" ; dir = File.expand_path("/tmp") ; puts dir ; stat = File.stat(dir) ; puts "directory? #{stat.directory?}" ; puts "writable? #{stat.writable?}" ; puts "world_writable? #{stat.world_writable?}" ; puts "sticky? #{stat.sticky?}" ; puts Dir.tmpdir ; puts Dir.mktmpdir'
  - bundle install --without system_tests --path /bundle --jobs $(nproc)
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

syntax:
  image: puppet_module_testing:latest
  script:
    - bundle exec rake syntax check:symlinks check:git_ignore check:dot_underscore
  variables:
    PUPPET_GEM_VERSION: '~> 6'

unit:
  image: puppet_module_testing:latest
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 6'

